### ISSUE TITLE
Debian package release

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev-lang-python#655]
Sorry for the short notice, but it would be great if we could get a new debian package released by this weekend (2019-08-18). I would like to create a new SD card image that will become the main download (after some testing of course).

**Comment by WasabiFan** [comment]
Agreed, and will-do. I'm returning from China tomorrow and intend to test all the new stuff out and publish a release. From here my Internet connection is inconsistent and I don't have easy access to my packaging VM so I've been putting it off until I'm back.

**Comment by WasabiFan** [comment]
FYI -- I'm actively working on this and should have the package published before I go to sleep tonight.

**Comment by EZ312** [comment]
Will it include the MoveTank.follow_line. I have troubles to use that in the latest debian package (5/30)

**Comment by WasabiFan** [comment]
@dlech I've published the package and done a cursory test.

@EZ312 Yes, that is included for the first time in this release. To upgrade, run `sudo apt update && sudo apt install python3-ev3dev2 micropython-ev3dev2`. Let us know how it works!

**Comment by bpmerkel** [comment]
I updated my EV3 this morning and found that console.mpy and stopwatch.mpy
didn't make it into /usr/lib/micropython/ev3dev2... so found those files
were missing from the debian/rules makefile. PR now awaits you... and
perhaps another release (before David builds a new image!?)

--
Brady P. Merkel
brady@merkel.net
Go Gators! --;==;<

**Comment by EZ312** [comment]
Our group just started using Python3 and we use this place to get the image: https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/ . I didn't see a new build yet. 
To run sudo apt update && sudo apt install python3-ev3dev2 micropython-ev3dev2, I assume we need the EV3 connected to the internet, and we can use putty to upgrade? We are pretty new to this and is there some doc  can help us? Thanks

**Comment by WasabiFan** [comment]
Ah yes, sorry @EZ312 — that would require internet access. We have guides here: https://www.ev3dev.org/docs/networking/

You would run those commands via PuTTY or via the SSH terminal in vscode, after getting internet access.

Otherwise, if you wait a few days @dlech will publish a new image which you can flash onto your SD card that includes the new library. So if you don't want to deal with getting connected to the internet you can just wait a few days and reflash your card.

If you have further questions please open a new issue so we can keep it separate from this one.

**Comment by bpmerkel** [comment]
Hey @EZ312 . The Seshan Brothers (of ev3lessons.com fame) have published a walkthrough presentation to get set up. See https://drive.google.com/open?id=1glQM_AN2_KDCzN0LXghCGTtaM3dpW5Gr. For great code examples, check out the links from the repo's home page as well as the FAQ.

**Comment by WasabiFan** [comment]
`2.0.0-beta5` version with uPy fix released to archives and PyPi.

**Comment by bpmerkel** [comment]
Just validated beta5 on my EV3... I see console.mpy and stopwatch.mpy now
up-to-date. w00t!

When do the docs get re-rendered and deployed? I still see beta3 deployed:
https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/spec.html

--
Brady P. Merkel
brady@merkel.net
Go Gators! --;==;<

**Comment by WasabiFan** [comment]
> When do the docs get re-rendered and deployed? I still see beta3 deployed:

rTD needed some prodding, apparently. I've manually re-triggered a build and while I was at it I fixed some defaults that pointed to the old jessie branch.
